### PR TITLE
Use epsilon comparison instead of rounding

### PR DESCRIPTION
**Pull request by emersion**
Use the formula `abs(a - b) < epsilon` to check whether two floating-point values are equal.

### CODE REVIEW

**Comment by aiAdrian** [comment]
Looks good for the validation side, but does it also resolve the epsilon issue when the user enter any floating point number, for example: 
he like to enter 

128.4 = 2h 8min und 24s => console.log((128.4) % 60); => 8.400000000000006 which is not correct w.r.t. business 8.4 would be fine. but the 8.40000000000000**6** must be avoided.

**Comment by louisgreiner** [comment]
I does look good for validation and visualisation in netzgrafik and perlenkette components, even with weirder figures and changing the number of decimal displayed

**Comment by emersion** [comment]
@aiAdrian, what do you mean exactly? Are you concerned about 8.400000000000006 getting saved into the store/database?

I personally think we should never care about rounding issues in internal code (intermediary values, computations, etc), and we should only care about them right at the end, when we actually display the value to the user (in that case, we want to round according to `getTimeDisplayPrecision()`) or compare it (in that case, compare with an epsilon with the formula in this PR).

Does that make sense?

**Comment by aiAdrian** [comment]
Yes, indeed i care about storing those values. Especially they make no sense. Under the assumption the stored value gets further exported to 3rd party it would good having at least in the database (JSON) "correct" data. This isn't related to the solved validation question. The addressed problem gets solved with #168

**Pull request merged**
